### ISSUE TITLE
Revise MA Impairment Layer

### ISSUE THREAD

**Issue by walkerjeffd** [Conte-Ecology/shedsICE_Deerfield#11]
Currently showing all categories from the 303(d) shapefile. But most are category 2 or 3 (either meets some or all uses, or not enough information for assessment). There are a few reaches with category 5 (impaired for one or more uses). These impairments include fecal coliform, low pH, physical habitat substrate alteration. I think we only want to show category 5, but do we want all of these impairment causes?

**Comment by rachelakatz** [comment]
I think just including category 5 impaired streams is sufficient for now.
Like the "resiliency problems" layer - can we just show the reaches in this category and then have a table with the specific causes? I don't recall this being very many streams, and thus may not be super interesting from a visualization stand point to partition the causes.
