### ISSUE TITLE
Add VT Impairment Layer

### ISSUE THREAD

**Issue by walkerjeffd** [Conte-Ecology/shedsICE_Deerfield#9]
Add 303(d) for VT: http://data.vtanr.opendata.arcgis.com/datasets/90a559b8f2514ae3aa90a6b70dea37f0_107

Make a table of impairment causes for VT and MA

**Comment by rachelakatz** [comment]
Similar to the 303d List for MA - just label the streams as impaired and have a table available for details if needed during the workshop about causes.
